name: CI for .NET App

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - github-actions

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./backend

      - name: Build
        run: dotnet build --no-restore ./backend

      - name: Run tests
        run: dotnet test --no-build --verbosity normal ./backend
